(function () {
    'use strict';

    const root = document.documentElement;
    const themeToggle = document.getElementById('themeToggle');
    const langToggle = document.getElementById('langToggle');

    const savedTheme = localStorage.getItem('theme') || 'dark';
    root.setAttribute('data-theme', savedTheme);

    themeToggle?.addEventListener('click', () => {
        const next = root.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
        root.setAttribute('data-theme', next);
        localStorage.setItem('theme', next);
    });

    const yearEl = document.getElementById('year');
    if (yearEl) yearEl.textContent = new Date().getFullYear();

    const i18n = {
        en: {
            back: 'Back to Home',
            'hero.title': 'Retrieval-Augmented Manipulation',
            'hero.venue': 'Science Robotics · CUHK',
            'hero.tagline': 'Object discovery, 3D reconstruction, template retrieval, and trajectory execution for object-centric robot manipulation',
            'hero.links.code': 'GitHub',
            'hero.links.paper': 'Paper',
            'hero.links.article': 'CUHK article',
            'm.tasks': '14 / 31',
            'm.tasksLabel': 'paper scale: tasks / objects',
            'm.stages': '4',
            'm.stagesLabel': 'runtime stages',
            'm.views': '128',
            'm.viewsLabel': 'template views per object',
            'm.k': '5',
            'm.kLabel': 'RAM-K candidates',
            'overview.title': 'Overview',
            'overview.p1': 'The public RAM code path treats manipulation as a retrieval problem first and a motion problem second: step1_grounding finds object instances in a live RGB frame, step2_ram lifts them into an explicit object-centric 3D representation, step3_planning turns that geometry into VLM subgoals, and step4_conducting converts those subgoals into Fairino waypoints.',
            'overview.p2': 'The key boundary is the object contract, not the robot SDK. <code>config/config.yaml</code> pins <code>ram_k=5</code>, <code>foundation_model=dinov2-b14</code>, <code>feat_layer=[7,9,11]</code>, <code>img_size=224</code>, <code>n_pts=1024</code>, and <code>planner.map_size=100</code>, so the entire stack has a fixed retrieval and planning shape.',
            'overview.scope': '<i class="fa-solid fa-user-pen"></i>My scope: I mined the public repo, reconstructed the four-stage data flow, and translated the code into a portfolio page. I did not retrain the backbone or fabricate benchmark numbers.',
            'overview.result': '<i class="fa-solid fa-bullhorn"></i>The paper frames the system for zero-shot real-world robot execution, spatially aware manipulation from a single 2D image, and adaptive replanning under physical constraints.',
            'architecture.title': 'Architecture',
            'architecture.cap': 'The runtime binds semantic discovery to geometry through GroundingDINO + SAM2, VGGT-1B, RAMNet, a VLM planner, and a deterministic trajectory layer.',
            'architecture.card1.title': 'RAMNet core',
            'architecture.card1.body': '<code>visions/ram/lib/network.py</code> keeps the DINOv2-B/14 backbone frozen, reads features from layers <code>[7,9,11]</code>, expands them to a 2304D embedding, and passes them through a 1-layer view adapter, a 4-layer shape encoder, a 4-layer map adapter, and a <code>2304 -> 512 -> 256 -> 3</code> deformation decoder.',
            'architecture.card2.title': 'Runtime split',
            'architecture.card2.body': '<code>step1_grounding.py</code> discovers objects, <code>step2_ram.py</code> estimates object pose and functional priors, <code>step3_planning.py</code> decomposes task language into constraints, and <code>step4_conducting.py</code> converts those constraints into robot waypoints.',
            'interfaces.title': 'Data Contracts',
            'interfaces.cap': 'Each stage writes inspectable artifacts, which makes the pipeline debuggable without hidden state.',
            'interfaces.th.stage': 'Stage',
            'interfaces.th.inputs': 'Inputs',
            'interfaces.th.outputs': 'Outputs',
            'interfaces.th.note': 'Note',
            'training.title': 'Training and Template Prep',
            'training.p1': 'Training uses BOP-style rendered scenes generated by BlenderProc: the README shows <code>--num-scenes 400</code> and <code>--views-per-scene 25</code>, while template preparation renders <code>128</code> views per object and stores the result as <code>obj_&lt;id&gt;.ply</code> plus <code>&lt;template_id&gt;.pkl</code>.',
            'training.p2': '<code>train_bop.py</code> builds RAMNet from the DINOv2-B/14 checkpoint, freezes the foundation model, and optimizes with <code>PoseNCE</code>, <code>NOCSLoss</code>, and <code>MatchLoss</code> for up to <code>50</code> epochs, <code>2000</code> train steps, batch size <code>4</code>, and learning rate <code>1e-4</code>.',
            'training.p3': 'The template side is object-category specific: <code>template.json</code> drives loading of <code>grasp_*</code>, <code>contact_point_*</code>, <code>hinge*</code>, and <code>plane_*</code> primitives, so the runtime can recover object-specific affordances instead of generic boxes.',
            'training.result': '<i class="fa-solid fa-layer-group"></i>The training path is closer to structured geometry fitting than end-to-end policy learning: the backbone stays frozen, while the adapters and geometric heads absorb category-specific priors.',
            'runtime.title': 'Runtime and Control',
            'runtime.cap': 'The execution layer stays explicit all the way to robot motion.',
            'runtime.p1': '<code>PathPlanner</code> uses a <code>100^3</code> voxel map, <code>max_steps=300</code>, <code>stop_threshold=0.001</code>, <code>target_map_weight=2</code>, <code>obstacle_map_weight=1</code>, and <code>pushing_skip_per_k=5</code>. <code>TrajectoryGenerator</code> converts voxels to base-frame poses, clamps Z to <code>table_height</code>, and emits robot waypoints with orientation and gripper state.',
            'runtime.p2': '<code>controller/fairino_arm.py</code> wraps the Fairino <code>Robot.RPC</code> interface and issues <code>MoveL</code> at velocity <code>60</code> and <code>MoveC</code> at velocity <code>20</code>, plus gripper commands. The result is a conventional motion layer rather than an end-to-end policy.',
            'runtime.p3': 'The runtime SVG keeps the four scripts separate, which is the right shape for debugging camera calibration, depth rescaling, template lookup, and constraint parsing independently.',
            'results.title': 'Results and Limits',
            'results.p1': 'The paper reports zero-shot real-world robot execution, spatially aware manipulation from a single 2D image, and adaptive replanning under physical constraints such as object size and collisions. It also reports CO3D generalization to unseen categories and robustness to shape and occlusion variation.',
            'results.p2': 'The local repo exposes the code path but not a benchmark logbook, so I treat the project as a reproducible public pipeline rather than a numbers-heavy claim.',
            'results.limit': '<i class="fa-solid fa-triangle-exclamation"></i>External checkpoints and large assets are required for a full run: Grounded-SAM-2, VGGT, DINOv2-B/14, the Fairino SDK, and the RAM template payloads are not vendored.',
            'highlights.title': 'What To Say In Interview',
            'highlights.card1.title': 'Object discovery',
            'highlights.card1.body': 'Explain how <code>RamVLM</code> filters categories, GroundingDINO returns <code>xyxy</code> boxes, and SAM2 turns them into masks on the source image plane.',
            'highlights.card2.title': 'Object-centric 3D',
            'highlights.card2.body': 'Explain how RAMNet fuses frozen DINOv2 tokens with position embeddings, <code>choose</code> indices, and template priors to predict view, NOCS, grasps, and planes.',
            'highlights.card3.title': 'Motion boundary',
            'highlights.card3.body': 'Explain how <code>ConstraintParser</code> turns VLM subgoals into gripper poses and how <code>PathPlanner</code> and <code>TrajectoryGenerator</code> convert them into Fairino motion.',
            'fig.arch': 'RAM architecture diagram showing the GroundingDINO + SAM2, VGGT-1B, RAMNet, planner, and Fairino execution stack.',
            'fig.runtime': 'RAM runtime visualization with the four scripts and their inspectable file contracts.',
            footer: '&copy; <span id="year"></span> Yueyi Chen. Powered by <a href="https://pages.github.com/" target="_blank" rel="noopener">GitHub Pages</a>.'
        },
        zh: {
            back: '返回主页',
            'hero.title': '检索增强式具身操作',
            'hero.venue': 'Science Robotics · CUHK',
            'hero.tagline': '面向物体中心机器人操作的物体发现、三维重建、模板检索和轨迹执行',
            'hero.links.code': '代码',
            'hero.links.paper': '论文',
            'hero.links.article': 'CUHK 文章',
            'm.tasks': '14 / 31',
            'm.tasksLabel': '论文规模：任务 / 物体',
            'm.stages': '4',
            'm.stagesLabel': '运行阶段',
            'm.views': '128',
            'm.viewsLabel': '每个物体的模板视角数',
            'm.k': '5',
            'm.kLabel': 'RAM-K 候选数',
            'overview.title': '概览',
            'overview.p1': '公开代码把操作流程拆成“先检索、后运动”两层：step1_grounding 在实时 RGB 帧中找出物体实例，step2_ram 将其抬升为显式的物体中心三维表示，step3_planning 把几何信息转成 VLM 子目标，step4_conducting 再把这些子目标转换成 Fairino 轨迹点。',
            'overview.p2': '真正的边界是物体合约，而不是机器人 SDK。<code>config/config.yaml</code> 固定了 <code>ram_k=5</code>、<code>foundation_model=dinov2-b14</code>、<code>feat_layer=[7,9,11]</code>、<code>img_size=224</code>、<code>n_pts=1024</code> 和 <code>planner.map_size=100</code>，所以整个系统的检索和规划形状都是确定的。',
            'overview.scope': '<i class="fa-solid fa-user-pen"></i>我的范围：我先把公开仓库完整拆解成四段数据流，再把代码翻译成作品页。我没有重训 backbone，也没有虚构 benchmark 数字。',
            'overview.result': '<i class="fa-solid fa-bullhorn"></i>论文将这个系统定位为零样本真机执行、单张 2D 图像下的空间化操作，以及在物体尺寸和碰撞等物理约束下的自适应重规划。',
            'architecture.title': '架构',
            'architecture.cap': '这个运行时把语义发现和几何执行通过 GroundingDINO + SAM2、VGGT-1B、RAMNet、VLM 规划器和确定性的轨迹层连接起来。',
            'architecture.card1.title': 'RAMNet 核心',
            'architecture.card1.body': '<code>visions/ram/lib/network.py</code> 冻结 DINOv2-B/14 backbone，从 <code>[7,9,11]</code> 三层取特征，拼成 2304D embedding，再依次经过 1 层 view adapter、4 层 shape encoder、4 层 map adapter 和 <code>2304 -> 512 -> 256 -> 3</code> 的 deformation decoder。',
            'architecture.card2.title': '运行时分工',
            'architecture.card2.body': '<code>step1_grounding.py</code> 负责找物体，<code>step2_ram.py</code> 负责估计物体位姿和功能先验，<code>step3_planning.py</code> 把语言拆成约束，<code>step4_conducting.py</code> 再把这些约束变成机器人轨迹点。',
            'interfaces.title': '数据合约',
            'interfaces.cap': '每个阶段都会写出可检查的中间产物，因此整条管线可以在没有隐藏状态的情况下调试。',
            'interfaces.th.stage': '阶段',
            'interfaces.th.inputs': '输入',
            'interfaces.th.outputs': '输出',
            'interfaces.th.note': '说明',
            'training.title': '训练与模板准备',
            'training.p1': '训练数据来自 BlenderProc 生成的 BOP 风格场景：README 给出的命令是 <code>--num-scenes 400</code> 和 <code>--views-per-scene 25</code>。模板准备则为每个物体渲染 <code>128</code> 个视角，并保存为 <code>obj_&lt;id&gt;.ply</code> 和 <code>&lt;template_id&gt;.pkl</code>。',
            'training.p2': '<code>train_bop.py</code> 用 DINOv2-B/14 checkpoint 初始化 RAMNet，冻结 foundation model，并用 <code>PoseNCE</code>、<code>NOCSLoss</code> 和 <code>MatchLoss</code> 训练，超参数是 <code>50</code> 个 epoch、<code>2000</code> 个 train step、batch size <code>4</code> 和学习率 <code>1e-4</code>。',
            'training.p3': '模板侧是类别特定的：<code>template.json</code> 决定加载 <code>grasp_*</code>、<code>contact_point_*</code>、<code>hinge*</code> 和 <code>plane_*</code> primitives，因此运行时恢复的是物体特定 affordance，而不是通用框。',
            'training.result': '<i class="fa-solid fa-layer-group"></i>这条训练路径更像结构化几何拟合，而不是端到端策略学习：backbone 保持冻结，adapter 和几何 head 吸收类别先验。',
            'runtime.title': '运行与控制',
            'runtime.cap': '执行层一直保持显式，直到机器人运动为止。',
            'runtime.p1': '<code>PathPlanner</code> 使用 <code>100^3</code> voxel map、<code>max_steps=300</code>、<code>stop_threshold=0.001</code>、<code>target_map_weight=2</code>、<code>obstacle_map_weight=1</code> 和 <code>pushing_skip_per_k=5</code>。<code>TrajectoryGenerator</code> 把 voxel 转成 base-frame 位姿，把 Z 限制在 <code>table_height</code>，再输出带朝向和夹爪状态的机器人 waypoint。',
            'runtime.p2': '<code>controller/fairino_arm.py</code> 封装 Fairino 的 <code>Robot.RPC</code> 接口，并以速度 <code>60</code> 调 <code>MoveL</code>、以速度 <code>20</code> 调 <code>MoveC</code>，外加夹爪命令。最终得到的是传统运动层，而不是端到端策略。',
            'runtime.p3': 'runtime SVG 把四个脚本分开，这正适合分别调试相机标定、深度重标定、模板查找和约束解析。',
            'results.title': '结果与限制',
            'results.p1': '论文报告了零样本真机执行、单张 2D 图像下的空间化操作，以及针对物体尺寸和碰撞等物理约束的自适应重规划；同时也报告了 CO3D 上对未见类别的泛化，以及对形状和遮挡变化的鲁棒性。',
            'results.p2': '本地仓库暴露的是完整代码路径，但没有 benchmark 日志本身，所以我把它当成可复现的公开管线，而不是数字堆砌型项目。',
            'results.limit': '<i class="fa-solid fa-triangle-exclamation"></i>完整运行还需要外部 checkpoint 和大体积资产：Grounded-SAM-2、VGGT、DINOv2-B/14、Fairino SDK 和 RAM template payload 都没有随仓库一起提交。',
            'highlights.title': '面试时怎么讲',
            'highlights.card1.title': '物体发现',
            'highlights.card1.body': '说明 <code>RamVLM</code> 如何筛选类别，GroundingDINO 如何返回 <code>xyxy</code> box，SAM2 又如何把它们变成 source image plane 上的 mask。',
            'highlights.card2.title': '物体中心 3D',
            'highlights.card2.body': '说明 RAMNet 如何把冻结的 DINOv2 token、position embedding、<code>choose</code> 索引和模板先验融合起来，预测 view、NOCS、grasp 和 plane。',
            'highlights.card3.title': '运动边界',
            'highlights.card3.body': '说明 <code>ConstraintParser</code> 如何把 VLM 子目标转成夹爪位姿，以及 <code>PathPlanner</code> 和 <code>TrajectoryGenerator</code> 如何把它们转成 Fairino 运动。',
            'fig.arch': 'RAM 架构图，展示 GroundingDINO + SAM2、VGGT-1B、RAMNet、planner 和 Fairino 执行栈。',
            'fig.runtime': 'RAM 运行时图，展示四个脚本及其可检查文件合约。',
            footer: '&copy; <span id="year"></span> 陈悦怡. 基于 <a href="https://pages.github.com/" target="_blank" rel="noopener">GitHub Pages</a> 搭建。'
        }
    };

    let currentLang = localStorage.getItem('lang') || 'en';

    function setLang(lang) {
        const dict = i18n[lang];
        if (!dict) return;

        document.querySelectorAll('[data-i18n]').forEach((el) => {
            const key = el.getAttribute('data-i18n');
            if (dict[key] != null) el.textContent = dict[key];
        });

        document.querySelectorAll('[data-i18n-html]').forEach((el) => {
            const key = el.getAttribute('data-i18n-html');
            if (dict[key] != null) el.innerHTML = dict[key];
        });

        document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
        if (langToggle) langToggle.textContent = lang === 'zh' ? 'EN' : '中';
        localStorage.setItem('lang', lang);
        currentLang = lang;
    }

    setLang(currentLang);

    langToggle?.addEventListener('click', () => {
        setLang(currentLang === 'en' ? 'zh' : 'en');
    });
})();
